// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List Manar Electro's public product catalog (smartphones, TV boxes, CCTV, mosque audio, accessories) with names in Arabic/English/French, price, category, tags, and availability.",
  inputSchema: {
    category: z.enum(["phones", "tv_box", "cctv", "mosque_audio", "conversion_service", "accessories"]).optional().describe("Optional category filter."),
    limit: z.number().int().min(1).max(200).optional().describe("Max results (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    let q = supabase.from("products").select("id,category,name_ar,name_en,name_fr,short_ar,short_en,short_fr,price,is_available,tags,emoji,image_url,sort_order").order("sort_order", { ascending: false }).limit(limit ?? 100);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tv-apps.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_tv_apps_default = defineTool2({
  name: "list_tv_apps",
  title: "List TV apps",
  description: "List the TV apps published by Manar Electro (name, description, image, download URL, free-or-subscription flag, and subscription note).",
  inputSchema: {
    only_free: z2.boolean().optional().describe("If true, return only free apps."),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_free, limit }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    let q = supabase.from("tv_apps").select("*").limit(limit ?? 100);
    if (only_free) q = q.eq("is_free", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { apps: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var SERVICES = [
  { id: "phone_repair", name: { ar: "\u0625\u0635\u0644\u0627\u062D \u0627\u0644\u0647\u0648\u0627\u062A\u0641", en: "Phone Repair", fr: "R\xE9paration t\xE9l\xE9phone" }, startingPrice: "1,500 DA" },
  { id: "tv_box_setup", name: { ar: "\u062A\u0647\u064A\u0626\u0629 TV Box \u0648 \u0627\u0644\u0633\u064A\u0631\u0641\u0631\u0627\u062A", en: "TV Box & Server Setup", fr: "Configuration TV Box & serveurs" }, startingPrice: "1,000 DA" },
  { id: "cctv_installation", name: { ar: "\u062A\u0631\u0643\u064A\u0628 \u0643\u0627\u0645\u064A\u0631\u0627\u062A \u0627\u0644\u0645\u0631\u0627\u0642\u0628\u0629", en: "CCTV Installation", fr: "Installation CCTV" } },
  { id: "mosque_audio_installation", name: { ar: "\u062A\u0631\u0643\u064A\u0628 \u0627\u0644\u0623\u0646\u0638\u0645\u0629 \u0627\u0644\u0633\u0645\u0639\u064A\u0629 \u0644\u0644\u0645\u0633\u0627\u062C\u062F", en: "Mosque Audio Installation", fr: "Installation audio de mosqu\xE9e" } },
  { id: "cassette_to_usb", name: { ar: "\u062A\u062D\u0648\u064A\u0644 \u0623\u0634\u0631\u0637\u0629 VHS \u0625\u0644\u0649 USB/DVD", en: "VHS to USB/DVD Conversion", fr: "Conversion VHS vers USB/DVD" } }
];
var list_services_default = defineTool3({
  name: "list_services",
  title: "List services",
  description: "List the technical services Manar Electro offers, with multilingual names and starting price when available.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var CONTACT = {
  shop_name: "Manar Electro",
  location: "B\xE9char, Algeria",
  phone: "+213671995077",
  whatsapp: "https://wa.me/213671995077",
  facebook: "https://www.facebook.com/manardjm",
  tiktok: "https://www.tiktok.com/@merabtihouari",
  maps: "https://maps.app.goo.gl/VxhXsABYR4CxAN3E7",
  coordinates: { lat: 31.617842, lng: -2.207584 }
};
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get shop contact info",
  description: "Return Manar Electro's public contact details: phone, WhatsApp, Facebook, TikTok, map location, and coordinates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACT) }],
    structuredContent: CONTACT
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "manar-electro-mcp",
  title: "Manar Electro",
  version: "0.1.0",
  instructions: "Public tools for the Manar Electro shop (B\xE9char, Algeria): browse products, TV apps, services, and get contact/location info. All data is read-only and public.",
  tools: [list_products_default, list_tv_apps_default, list_services_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
